// <auto-generated />
using System;
using ExtremeHelp.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExtremeHelp.Api.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20250608201005_InitialDatabase")]
    partial class InitialDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExtremeHelp.Api.Models.Alerta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CD_ALERTA");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataPublicacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_PUBLICACAO");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("DS_MENSAGEM");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("DS_TITULO");

                    b.HasKey("Id");

                    b.ToTable("T_EH_ALERTA");
                });

            modelBuilder.Entity("ExtremeHelp.Api.Models.DicaCategoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("T_EH_DICA_CATEGORIA");
                });

            modelBuilder.Entity("ExtremeHelp.Api.Models.DicaPreparacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CD_DICA");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DS_CONTEUDO");

                    b.Property<int>("DicaCategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("DS_TITULO");

                    b.Property<DateTime>("UltimaAtualizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_ULTIMA_ATUALIZACAO");

                    b.HasKey("Id");

                    b.HasIndex("DicaCategoriaId");

                    b.ToTable("T_EH_DICA_PREPARACAO");
                });

            modelBuilder.Entity("ExtremeHelp.Api.Models.DicaPreparacao", b =>
                {
                    b.HasOne("ExtremeHelp.Api.Models.DicaCategoria", "Categoria")
                        .WithMany("Dicas")
                        .HasForeignKey("DicaCategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("ExtremeHelp.Api.Models.DicaCategoria", b =>
                {
                    b.Navigation("Dicas");
                });
#pragma warning restore 612, 618
        }
    }
}
